// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.user_id", "2db5afea-fa63-4097-87ee-2da9fd0f2b22");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1573739043);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1573737955);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1573738923);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1573738075);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1517);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1573737925);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0880272e-47c0-418a-bfe7-1541fc88fd2d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1573737973072");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1573739762072");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1573737929266");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1573741529266");
user_pref("browser.search.region", "ES");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1573741980");
user_pref("browser.slowStartup.averageTime", 1182);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "https://bib.us.es/bellasartes");
user_pref("browser.startup.homepage_override.buildID", "20191030021342");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1573741980);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1573737927272");
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "ed0b99cc8a8b45b696d3269a07311579");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191030021342");
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.privatebrowsing.notification", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"84c02148-3fd5-42d8-80c7-11de4ab48b57\",\"screenshots@mozilla.org\":\"8562bc39-0f1c-4f0a-b1be-c2ebe1ac611b\",\"webcompat-reporter@mozilla.org\":\"c9359c2e-ad69-4375-a948-556d0bc62042\",\"webcompat@mozilla.org\":\"c2351b0a-906e-443c-a5e7-e6b072261cc2\",\"default-theme@mozilla.org\":\"80858022-ea7d-4b53-b1b7-9d320ee4182d\",\"google@search.mozilla.org\":\"28fb75fe-09af-4ef9-adef-ccfd96a5ba5d\",\"bing@search.mozilla.org\":\"c68cf873-987c-41d3-8a91-7835cad2b6d1\",\"drae@search.mozilla.org\":\"9fd5d726-42dd-4e97-af36-abf02a4e4ea9\",\"ddg@search.mozilla.org\":\"78eaff73-2265-4c11-905d-cd3aa945f687\",\"ebay@search.mozilla.org\":\"9ef6faf1-7dea-42a1-a3ac-45854774d634\",\"twitter@search.mozilla.org\":\"ecfeb507-c477-4b7a-8e5f-e41147d61635\",\"wikipedia@search.mozilla.org\":\"8cfa0bbb-93b1-4ef8-9c31-6f170c8cdc7b\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "70.0.1");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x5917");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "23.20.16.5038");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.history.custom", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x5917");
user_pref("sanity-test.driver-version", "23.20.16.5038");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20191030021342");
user_pref("security.sandbox.content.tempDirSuffix", "{80a70520-38b8-4d85-bb70-f766561c6474}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{3c154541-d883-4a8a-9cf2-47c3d4328277}");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1573741979);
user_pref("toolkit.telemetry.cachedClientID", "3195df94-0f94-4837-bfdf-2b4debd57b41");
user_pref("toolkit.telemetry.previousBuildID", "20191030021342");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
